apiVersion: v2
name: keycloak-client-operator
description: A Helm chart for Keycloak Client Operator
type: application
version: 0.3.0
appVersion: 0.1.0
keywords:
  - keycloak
  - operator
  - kubernetes
home: https://github.com/pewty/keycloak-client-operator
maintainers:
  - name: pewty
