apiVersion: keycloak.pewty.fr/v1
kind: Client
metadata:
  labels:
    app.kubernetes.io/name: keycloak-client-operator
    app.kubernetes.io/managed-by: kustomize
  name: client-sample
spec:
  realm: "energypool"
  client:
    clientId: "my-client"
    name: "My Client"
    enabled: true
    protocol: "openid-connect"
    publicClient: false
    directAccessGrantsEnabled: true
    redirectUris:
      - "https://myapp.example.com/*"
    webOrigins:
      - "*"
    secret: "my-client-secret"
