{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "keycloak-client-operator.fullname" . }}-manager-rolebinding
  labels:
    {{- include "keycloak-client-operator.labels" . | nindent 4 }}
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "keycloak-client-operator.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "keycloak-client-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
